llm:
  base_url: https://api.deepseek.com
  api_key: sk-5a4c805e2d3b4eb48f1d0bcc5a9a961e
  model: deepseek-v4-flash
  embedding:
    base_url: https://api.siliconflow.cn/v1
    model: BAAI/bge-m3
    api_key: sk-glnsforuahxkjbxpyvojniplbxmppbgszwhvfulyldspukrk
  check_model: deepseek-v4-flash
  reasoning_effort: null
